export const CATEGORIES = [
    {'id':'other', name_fr:'Autre',name_nl:'Overige'},
    {'id':'covid', name_fr:'Covid-19',name_nl:'Covid-19'},
    {'id':'anatocism', name_fr:'Anatocisme',name_nl:'Anatocisme'},
]

export const YEARS = [
    2020,
    2019,
    2018,
    2017,
    2016,
    2015,
    2014,
    2013,
    2012,
    2011,
    2010,
    2009,
    2008,
    2007,
    2006,
    2005,
    2004,
    2003,
    2002,
    2001,
    2000,
];

export const COURTS = [
    {"id": "GHCC", "name_fr": "Cour Constitutionnelle", "name_nl": "Grondwettelijk Hof"},
    {"id": "RSCE", "name_fr": "Conseil d'État", "name_nl": "Raad van State"},
    {"id": "CASS", "name_fr": "Cour de Cassation", "name_nl": ""},
    {"id": "CABRL", "name_fr": "Cour d'appel du ressort de Bruxelles", "name_nl": ""},
    {"id": "CALIE", "name_fr": "Cour d'appel du ressort de Liège", "name_nl": ""},
    {"id": "CAMON", "name_fr": "Cour d'appel du ressort de Mons", "name_nl": ""},
    {"id": "HBANT", "name_fr": "Cour d'appel du ressort d'Anvers", "name_nl": ""},
    {"id": "HBGNT", "name_fr": "Cour d'appel du ressort de Gand", "name_nl": ""},
    {"id": "AHANT", "name_fr": "Cour du travail d'Anvers et division Hasselt", "name_nl": ""},
    {"id": "AHGNT", "name_fr": "Cour du travail de Gand et division Bruges", "name_nl": ""},
    {"id": "CTBRL", "name_fr": "Cour du travail de Bruxelles", "name_nl": ""},
    {"id": "CTLIE", "name_fr": "Cour du travail de Liège et divisions Namur - Neufchâteau", "name_nl": ""},
    {"id": "CTMON", "name_fr": "Cour du travail de Mons", "name_nl": ""},
    {"id": "EAANT", "name_fr": "Tribunal de première instance d'Anvers", "name_nl": ""},
    {"id": "EAWVL", "name_fr": "Tribunal de première instance de Flandre Occidentale", "name_nl": ""},
    {"id": "EAOVL", "name_fr": "Tribunal de première instance de Flandre Orientale", "name_nl": ""},
    {"id": "EALIM", "name_fr": "Tribunal de première instance du Limbourg", "name_nl": ""},
    {"id": "EALEU", "name_fr": "Tribunal de première instance de Louvain", "name_nl": ""},
    {"id": "EABRL", "name_fr": "Tribunal de première instance néerlandophone de Bruxelles", "name_nl": ""},
    {"id": "PIBRL", "name_fr": "Tribunal de première instance francophone de Bruxelles", "name_nl": ""},
    {"id": "PIHAI", "name_fr": "Tribunal de première instance du Hainaut", "name_nl": ""},
    {"id": "PINAM", "name_fr": "Tribunal de première instance de Namur", "name_nl": ""},
    {"id": "TREUP", "name_fr": "Tribunal d'Eupen", "name_nl": ""},
    {"id": "PILIE", "name_fr": "Tribunal de première instance de Liège", "name_nl": ""},
    {"id": "PILUX", "name_fr": "Tribunal de première instance du Luxembourg", "name_nl": ""},
    {"id": "PIBRW", "name_fr": "Tribunal de première instance du Brabant Wallon", "name_nl": ""},
    {"id": "ARANT", "name_fr": "Tribunal du travail d'Anvers", "name_nl": ""},
    {"id": "ARGNT", "name_fr": "Tribunal du travail de Gand", "name_nl": ""},
    {"id": "ARLEU", "name_fr": "Tribunal du travail de Louvain", "name_nl": ""},
    {"id": "ARBRL", "name_fr": "Tribunal du travail néerlandophone de Bruxelles", "name_nl": ""},
    {"id": "TTBRL", "name_fr": "Tribunal du travail francophone de Bruxelles", "name_nl": ""},
    {"id": "TTHAI", "name_fr": "Tribunal du travail du Hainaut", "name_nl": ""},
    {"id": "TTLIE", "name_fr": "Tribunal du travail de Liège", "name_nl": ""},
    {"id": "TTBRW", "name_fr": "Tribunal du travail du Brabant Wallon", "name_nl": ""},
    {"id": "KHANT", "name_fr": "Tribunal de Commerce d'Anvers", "name_nl": ""},
    {"id": "KHBRL", "name_fr": "Tribunal de Commerce néerlandophone de Bruxelles", "name_nl": ""},
    {"id": "TCBRL", "name_fr": "Tribunal de Commerce francophone de Bruxelles ", "name_nl": ""},
    {"id": "KHLEU", "name_fr": "Tribunal de Commerce de Louvain", "name_nl": ""},
    {"id": "TCBRW", "name_fr": "Tribunal de Commerce du Brabant Wallon ", "name_nl": ""},
    {"id": "KHGNT", "name_fr": "Tribunal de Commerce de Gand", "name_nl": ""},
    {"id": "TCLIE", "name_fr": "Tribunal de Commerce de Liège", "name_nl": ""},
    {"id": "TCHAI", "name_fr": "Tribunal de Commerce du Hainaut", "name_nl": ""},
    {"id": "TELIE", "name_fr": "Tribunal de Commerce de Liège", "name_nl": ""},
    {"id": "TEBRL", "name_fr": "Tribunal de Commerce francophone de Bruxelles ", "name_nl": ""},
    {"id": "TEBRW", "name_fr": "Tribunal de Commerce du Brabant Wallon ", "name_nl": ""},
    {"id": "TEHAI", "name_fr": "Tribunal de Commerce du Hainaut", "name_nl": ""},
    {"id": "ORANT", "name_fr": "Tribunal du travail d'Anvers", "name_nl": ""},
    {"id": "ORGNT", "name_fr": "Tribunal de Commerce de Gand", "name_nl": ""},
    {"id": "ORBRL", "name_fr": "Tribunal du travail néerlandophone de Bruxelles", "name_nl": ""},
    {"id": "ORLEU", "name_fr": "Tribunal du travail de Louvain", "name_nl": ""},
    {"id": "NTRCND", "name_fr": "Conseil national de discipline ", "name_nl": ""},
    {"id": "GBAPE", "name_fr": "Autorité de protection des données ", "name_nl": ""},
    {"id": "COPRIV", "name_fr": "Commission pour la Protection de la Vie privée", "name_nl": ""},
    {"id": "COHSAV", "name_fr": "Commission pour l'aide financière aux victimes d'actes intentionnels de violence et aux sauveteurs occasionnels", "name_nl": ""},
    {"id": "COVHDP", "name_fr": "Commission d'indemnisation de la détention préventive inopérante", "name_nl": ""},
    {"id": "PRANT", "name_fr": "Tribunal de police d'Anvers", "name_nl": "Politierechtbank Antwerpen"},
    {"id": "PRWVL", "name_fr": "Tribunal de police de Flandre Occidentale", "name_nl": "Politierechtbank West-Vlaanderen"},
    {"id": "PROVL", "name_fr": "Tribunal de police de Flandre Orientale", "name_nl": "Politierechtbank Oost-Vlaanderen"},
    {"id": "PRLIM", "name_fr": "Tribunal de police du Limbourg", "name_nl": "Politierechtbank Limburg"},
    {"id": "PRLEU", "name_fr": "Tribunal de police de Louvain", "name_nl": "Politierechtbank Leuven"},
    {"id": "PRHAL", "name_fr": "Tribunal de police de Halle", "name_nl": "Politierechtbank Halle"},
    {"id": "PRVIL", "name_fr": "Tribunal de police de Vilvoorde", "name_nl": "Politierechtbank Vilvoorde"},
    {"id": "PRBRL", "name_fr": "Tribunal de police néerlandophone de Bruxelles", "name_nl": "Nederlandstalige politierechtbank Brussel"},
    {"id": "TPBRL", "name_fr": "Tribunal de police francophone de Bruxelles", "name_nl": "Franstalige politierechtbank Brussel"},
    {"id": "TPHAI", "name_fr": "Tribunal de police du Hainaut", "name_nl": "Politierechtbank Henegouwen"},
    {"id": "TPNAM", "name_fr": "Tribunal de police de Namur", "name_nl": "Politierechtbank Namen"},
    {"id": "TPLIE", "name_fr": "Tribunal de police de l'arrondissement de Liège", "name_nl": "Politierechtbank Luik"},
    {"id": "TPEUP", "name_fr": "Tribunal de police d'Eupen", "name_nl": "Politierechtbank Eupen"},
    {"id": "TPLUX", "name_fr": "Tribunal de police du Luxembourg", "name_nl": "PolitierechtbankLuxemburg"},
    {"id": "TPBRW", "name_fr": "Tribunal de police du Brabant Wallon", "name_nl": "Politierechtbank Waals Brabant"},
]
